// ---------------------------------------------------------------------------
// Ocean eReferral Dashboard – shared constants
// ---------------------------------------------------------------------------

// ── Field mapping objects ───────────────────────────────────────────────────
// These normalise Excel column headers (case-insensitive, various formats) to
// canonical camelCase field names used throughout the application.

export const LISTING_MAP: Record<string, string> = {
  ref: 'ref', title: 'title', city: 'city', province: 'province',
  postalcode: 'postalCode', postalCode: 'postalCode',
  healthregion: 'healthRegion', healthRegion: 'healthRegion',
  ereferrals: 'eReferrals', eReferrals: 'eReferrals',
  econsults: 'eConsults', eConsults: 'eConsults',
  ccenabled: 'CCEnabled', CCEnabled: 'CCEnabled',
  ccsek: 'CCSEK', CCSEK: 'CCSEK',
  listingrepositorycontribution: 'listingRepositoryContribution',
  listingRepositoryContribution: 'listingRepositoryContribution',
  trusteecustodian: 'trusteeCustodian', trusteeCustodian: 'trusteeCustodian',
  'ra approval status': 'raApprovalStatus', 'RA Approval Status': 'raApprovalStatus',
  'test mode': 'testMode', 'Test Mode': 'testMode',
  sitenum: 'siteNum', siteNum: 'siteNum',
  sitename: 'siteName', siteName: 'siteName',
  listingtype: 'listingType', listingType: 'listingType',
  'ereferral management': 'eReferralManagement', 'eReferral management': 'eReferralManagement',
  catchmentarea: 'catchmentArea', catchmentArea: 'catchmentArea',
  raclinicianscount: 'raCliniciansCount', raCliniciansCount: 'raCliniciansCount',
  organizationtitle: 'organizationTitle', organizationTitle: 'organizationTitle',
  integratedsystem: 'integratedSystem', integratedSystem: 'integratedSystem',
  services: 'services', language: 'language',
  claimedbyuser: 'claimedByUser', claimedByUser: 'claimedByUser',
  'claimed by user': 'claimedByUser', 'Claimed By User': 'claimedByUser',
  clinicianprofessionalid: 'clinicianProfessionalId',
  clinicianProfessionalId: 'clinicianProfessionalId',
  'clinician Professional ID': 'clinicianProfessionalId',
  'clinician professional id': 'clinicianProfessionalId',
};

export const SITE_MAP: Record<string, string> = {
  'site number': 'siteNumber', 'Site Number': 'siteNumber',
  'site name': 'siteName', 'Site Name': 'siteName',
  '# of approved listings': 'approvedListings', '# of Approved Listings': 'approvedListings',
  'patient messaging coverage enabled': 'patientMessagingEnabled',
  'Patient Messaging Coverage Enabled': 'patientMessagingEnabled',
  '# of patient messaging licences': 'patientMessagingLicences',
  '# of Patient Messaging Licences': 'patientMessagingLicences',
  'online booking coverage enabled': 'onlineBookingEnabled',
  'Online Booking Coverage Enabled': 'onlineBookingEnabled',
  '# of online booking licences': 'onlineBookingLicences',
  '# of Online Booking Licences': 'onlineBookingLicences',
  'estimated total licence fees per month ($)': 'estimatedFees',
  'Estimated Total Licence Fees per Month ($)': 'estimatedFees',
  emr: 'emr', EMR: 'emr',
  'organization address': 'organizationAddress', 'Organization Address': 'organizationAddress',
  'validated site': 'validatedSite', 'Validated Site': 'validatedSite',
  'site validation status changed by': 'validationChangedBy',
  'Site Validation Status Changed By': 'validationChangedBy',
  'site validation status changed on': 'validationChangedOn',
  'Site Validation Status Changed On': 'validationChangedOn',
};

export const USER_MAP: Record<string, string> = {
  username: 'userName', UserName: 'userName',
  name: 'name', Name: 'name',
  cliniciantype: 'clinicianType', ClinicianType: 'clinicianType',
  phone: 'phone', Phone: 'phone',
  'professional id': 'professionalId', 'Professional ID': 'professionalId',
  email: 'email', Email: 'email',
  'site names': 'siteNames', 'Site Names': 'siteNames',
  'site numbers': 'siteNumbers', 'Site Numbers': 'siteNumbers',
  dateofagreement: 'dateOfAgreement', DateOfAgreement: 'dateOfAgreement',
  licenseversion: 'licenseVersion', LicenseVersion: 'licenseVersion',
  'hinp agreement signatory': 'hinpSignatory', 'HINP Agreement Signatory': 'hinpSignatory',
  valid: 'valid', Valid: 'valid',
};

export const REFERRAL_MAP: Record<string, string> = {
  sitenum: 'siteNum', siteNum: 'siteNum',
  srcsitenum: 'srcsiteNum', srcsiteNum: 'srcsiteNum',
  srcSiteName: 'srcSiteName', srcsitename: 'srcSiteName',
  referraltargetref: 'referralTargetRef', referralTargetRef: 'referralTargetRef',
  referredbyusername: 'referredByUserName', referredByUserName: 'referredByUserName',
  referredbyuserfullname: 'referredByUserFullName', referredByUserFullName: 'referredByUserFullName',
  referralcreationdate: 'referralCreationDate', referralCreationDate: 'referralCreationDate',
  referralstate: 'referralState', referralState: 'referralState',
  referralref: 'referralRef', referralRef: 'referralRef',
  recipientname: 'recipientName', recipientName: 'recipientName',
  referralsource: 'referralSource', referralSource: 'referralSource',
  senttotestlisting: 'sentToTestListing', sentToTestListing: 'sentToTestListing',
  completionstate: 'completionState', completionState: 'completionState',
  referrercliniciantype: 'referrerClinicianType', referrerClinicianType: 'referrerClinicianType',
  referrername: 'referrerName', referrerName: 'referrerName',
  accepteddate: 'acceptedDate', acceptedDate: 'acceptedDate',
  completeddate: 'completedDate', completedDate: 'completedDate',
  inbound: 'inbound',
  econsultoutcome: 'eConsultOutcome', eConsultOutcome: 'eConsultOutcome',
  initialrecipientname: 'initialRecipientName', initialRecipientName: 'initialRecipientName',
  initialreferraltargetref: 'initialReferralTargetRef', initialReferralTargetRef: 'initialReferralTargetRef',
  referrerurgency: 'referrerUrgency', referrerUrgency: 'referrerUrgency',
  recipientpriority: 'recipientPriority', recipientPriority: 'recipientPriority',
  patientcity: 'patientCity', patientCity: 'patientCity',
  patientprovince: 'patientProvince', patientProvince: 'patientProvince',
  referrercity: 'referrerCity', referrerCity: 'referrerCity',
  referrerprovince: 'referrerProvince', referrerProvince: 'referrerProvince',
  recipientprovince: 'recipientProvince', recipientProvince: 'recipientProvince',
  referrerprofessionalid: 'referrerProfessionalId', referrerProfessionalId: 'referrerProfessionalId',
  currenthealthservice: 'currentHealthService', currentHealthService: 'currentHealthService',
  initialhealthservice: 'initialHealthService', initialHealthService: 'initialHealthService',
  externalserviceid: 'externalServiceId', externalServiceId: 'externalServiceId',
};

// ── Diagnostic field sets ───────────────────────────────────────────────────
// The canonical fields actually consumed by the dashboard for each dataset.

export const USED_FIELDS: Record<string, Set<string>> = {
  listing: new Set([
    'ref', 'title', 'city', 'province', 'postalCode', 'healthRegion',
    'eReferrals', 'eConsults', 'CCEnabled', 'CCSEK',
    'listingRepositoryContribution', 'trusteeCustodian', 'raApprovalStatus',
    'testMode', 'siteNum', 'siteName', 'listingType', 'eReferralManagement',
    'catchmentArea', 'raCliniciansCount', 'organizationTitle',
    'integratedSystem', 'services', 'language', 'claimedByUser',
    'clinicianProfessionalId',
  ]),
  site: new Set([
    'siteNumber', 'siteName', 'approvedListings', 'patientMessagingEnabled',
    'patientMessagingLicences', 'onlineBookingEnabled', 'onlineBookingLicences',
    'estimatedFees', 'emr', 'organizationAddress', 'validatedSite',
    'validationChangedBy', 'validationChangedOn',
  ]),
  user: new Set([
    'userName', 'name', 'clinicianType', 'phone', 'professionalId', 'email',
    'siteNames', 'siteNumbers', 'dateOfAgreement', 'licenseVersion',
    'hinpSignatory', 'valid',
  ]),
  referral: new Set([
    'siteNum', 'srcsiteNum', 'srcSiteName', 'referralTargetRef',
    'referredByUserName', 'referredByUserFullName', 'referralCreationDate',
    'referralState', 'referralRef', 'recipientName', 'referralSource',
    'sentToTestListing', 'completionState', 'referrerClinicianType',
    'referrerName', 'acceptedDate', 'completedDate', 'inbound',
    'eConsultOutcome', 'initialRecipientName', 'initialReferralTargetRef',
    'referrerUrgency', 'recipientPriority', 'patientCity', 'patientProvince',
    'referrerCity', 'referrerProvince', 'recipientProvince',
    'referrerProfessionalId', 'currentHealthService', 'initialHealthService',
    'externalServiceId',
  ]),
};

// ── Field definitions ───────────────────────────────────────────────────────
// Human-readable descriptions of every known field, used for tooltips / docs.

export const FIELD_DEFS: Record<string, string> = {
  ref: 'Reference name/id for the listing.',
  title: 'The title of the listing.',
  serviceDescription: 'A free-text description of the services offered by the listing. This will typically show up in the healthmap as a description for the listing.',
  services: 'Services offered by the listing. These are pre-defined constants which indicate the services offered.  Healthservice constants, description, synonyms, loinc and snomed codes have been provided which indicate the appropriate healthservice constant to select.',
  line1: 'Street address of the listing',
  line2: 'Apt/unit number of the listing, if applicable',
  city: 'City address of the listing',
  province: 'Province address of the listing',
  postalCode: 'Postal code of the listing',
  phone: 'Phone number of listing',
  fax: 'Fax number of listing',
  email: 'email address of listing',
  website: 'Website of listing',
  notificationEmail: "The listing's eRequest Notification Email",
  claimedByUser: 'Indicates which user claimed the directory listing',
  clinicianSurname: 'Surname of clinician assigned to listing',
  clinicianFirstName: 'First name of clinician assigned to listing',
  clinicianProfessionalId: "Clinician's professional ID",
  organizationTitle: 'Organizations are set up by Ocean site and can be assigned to multiple listings which will enable senders see which listings might be related to which organizations',
  organizationRef: 'Organization reference ID – organizations are set up by site',
  integratedSystem: 'Indicates which external system the listing is integrated with',
  'geocode failure reason': "If listing's geocode fails, this field highlights the reason for failure",
  'eReferral management': 'Identifies how the eReferrals are managed for the directory listing in Ocean',
  listingRepositoryContribution: "Reflects the status of the directory listings contribution to the repository: 'CONTRIBUTING' indicates that all of the following 5 requirements have been met: 1) the \u2018Contribute data to repository\u2019 setting within the Directory\u2019s Listing\u2019s settings is enabled, 2) the \u2018Enable Ocean Cloud Connect\u2019 checkbox is enabled within the Ocean Site, 3) SEK entered in CC, 4) Site level contributing setting is enabled under \u201cManage Site Agreement\u201d, and 5) RA site has selected a repository other than \u201cNone\u201d. 'NOT_CONTRIBUTING' indicates that any one of requirements 1-4 in the bullet above has not been met. '{blank}' indicates that the Regional Authority has not set a repository (under RA Site > Admin > Regional Authority). If the repository is \u201cNone\u201d, this column will always be blank.",
  trusteeCustodian: "Indicates if and how the Ocean Site has identified themselves as a Trustee/Custodian within their Ocean Site configuration. 'TRUSTEE_CUSTODIAN' indicates that the Ocean Site has identified themselves as a Trustee/Custodidan by selecting the \u2018Yes, this site is a Trustee/Custodian\u2019 option. 'NON_TRUSTEE_CUSTODIAN' indicates that the Ocean Site has identified themselves as not being a Health Information Custodian by selecting the \u2018No, this site is not a Trustee/Custodian\u2019 option. 'UNSPECIFIED' indicates that the Directory Listing is currently accepting eReferrals, but the Ocean Site has not indicated whether or not they are a Health Information Custodian. 'NOT_ACCEPTING_EREFERRALS' indicates that the Directory Listing is not accepting eReferrals, regardless of Trustee/Custodian status.",
  siteNum: 'Site number in Ocean that listing is associated with',
  siteName: 'Site name in Ocean that listing is associated with',
  healthRegion: 'Health regions that a site belongs to pertaining to a Regional Authority, may not be applicable to listings outside of British Columbia',
  listingType: 'Defines the type of listing (e.g. STANDARD_CLINICAL_LISTING, RAPID_ACCESS_CLINIC, CENTRAL_INTAKE, REPOSITORY_FOR_REQUISITIONS)',
  catchmentArea: 'Indicating if a catchment area is set for the listing or not',
  eReferrals: "Indicates 'ENABLED' if at least one HSO on the listing has 'Accept eReferrals' set to \u2018Yes\u2019 and the listing is actively accepting eRequests (i.e., 'Accepting eRequests' within the Directory Listing is enabled). Indicates 'NOT ENABLED' otherwise.",
  eConsults: "Indicates 'ENABLED' if at least one HSO on the listing has 'Accept eConsults' set to \u2018Yes\u2019 and the listing is actively accepting eRequests (i.e., 'Accepting eRequests' within the Directory Listing is enabled). Indicates 'NOT ENABLED' otherwise.",
  externalId: 'This field populates the value from the Enablement > Integrations > External service ID setting in the listing',
  language: 'Includes the languages supported by the directory listing',
  raCliniciansCount: 'For listings that have applied to a Regional Authority, this field indicates the numbers of clinicians authorized to receive eReferrals and/or eConsults at this directory listing',
  raCliniciansComment: 'For listings that have applied to a Regional Authority, this field shows any additional information associated with the number of clinicians during the application',
  raCliniciansLastUpdated: 'For listings that have applied to a Regional Authority, this field indicates when the number of clinicians was last updated',
  managesWaitTimesAndIsCI: 'For listings that are configured as a Central Intake, this field indicates if the "Managed by Central Intake" wait time management functionality has been enabled (TRUE = enabled).',
  'RA Approval Status': 'The approval status of the listing. Can be one of: Pending, Approved, [blank].',
  'Test Mode': 'Indicates if Test Mode is enabled on the listing or not (TRUE = enabled)',
  regionalAuthoritySiteNum: 'The Ocean Site number for the Regional Authority Site that the listing has applied to and/or been approved under.',
  CCEnabled: 'Indicates if Ocean Cloud Connect is enabled or disabled for the Ocean Site, where "CC_ENABLED" = Yes and "CC_NOT_ENABLED" = No.',
  CCSEK: "Indicates if the Ocean Site's Shared Encryption Key is stored in Ocean Cloud Connect, where \"SEK_STORED\" = Yes and \"SEK_NOT_STORED\" = No.",
  integrationName: 'Name of the integration associated with the Directory Listing (if configured).',
  billingNum: 'Billing number of the clinician assigned to the listing',
  protectedDescriptionForClinicians: 'Information entered in the "Additional information for clinicians" setting of the Directory Listing.',
  'Site Number': 'The Ocean Site number.',
  'Site Name': 'The name of the Ocean Site.',
  '# of Approved Listings': 'The number of Directory Listings that have been approved by the Regional Authority.',
  'Patient Messaging Coverage Enabled': 'Indicates whether or not Patient Messaging licence coverage has been enabled by the Regional Authority, where TRUE represents enabled.',
  '# of Patient Messaging Licences': 'The number of Patient Messaging licences that have been enabled within the Ocean Site.',
  'Online Booking Coverage Enabled': 'Indicates whether or not Online Booking licence coverage has been enabled by the Regional Authority, where TRUE represents enabled.',
  '# of Online Booking Licences': 'The number of Online Booking licenses that have been enabled within the Ocean Site.',
  'Estimated Total Licence Fees per Month ($)': 'The estimated sum of licence fees per month in dollars that the Regional Authority has assumed responsibility for.',
  EMR: 'The EMR that the Ocean Site is integrated with, if any.',
  'Organization Address': 'The concatenated address information as set within the "Menu > Admin > Organization" fields of the Ocean Site.',
  'Validated Site': 'Indicates whether or not the "Validate this site" checkbox has been enabled for the Ocean Site within the Manage Site Agreement page.',
  'Site Validation Status Changed By': 'The Ocean username of the user that modified the "Validate this site" for the Ocean Site within the Manage Site Agreement page.',
  'Site Validation Status Changed On': 'The date that the "Validate this site" for the Ocean Site within the Manage Site Agreement page.',
  UserName: 'The Ocean account username.',
  Name: 'The full name of the user.',
  ClinicianType: 'The User Role as set within the Ocean user account.',
  Phone: 'The phone number associated with the manually entered Clinic Location within the Ocean user account.',
  'Professional ID': 'The Professional ID as set within the Ocean user account.',
  Email: 'The email address associated with the Ocean user account.',
  'Site Names': 'A list of the name(s) of each of the Ocean Site(s) that the user is associated with, separated by a semi-colon.',
  'Site Numbers': 'A list of the Ocean Site Number(s) of each the Ocean Site(s) that the user is associated with, separated by a semi-colon.',
  DateOfAgreement: "The date the user agreed to the Regional Authority's License Agreement.",
  LicenseVersion: 'The version of the License Agreement that the user agreed to.',
  'HINP Agreement Signatory': 'The Health Information Network Provider Agreement Signatory (Ontario-specific). This is a deprecated value.',
  Valid: 'The current validity of the agreement, where TRUE represents valid.',
};

// ── Theme colours ───────────────────────────────────────────────────────────
// Renamed from the original `clr` short-hand to descriptive property names.

export const COLORS = {
  background: '#0B1120',
  card: '#111827',
  border: '#1E293B',
  text: '#E2E8F0',
  muted: '#94A3B8',
  dimmed: '#64748B',
  accent: '#22D3EE',
  green: '#34D399',
  greenDark: '#065F46',
  greenGlow: 'rgba(52,211,153,0.15)',
  amber: '#FBBF24',
  red: '#F87171',
  purple: '#A78BFA',
  blue: '#60A5FA',
  accentGlow: 'rgba(34,211,238,0.12)',
} as const;

// ── Chart colour palette ────────────────────────────────────────────────────

export const CHART_PALETTE = [
  COLORS.accent,
  COLORS.green,
  COLORS.purple,
  COLORS.amber,
  COLORS.blue,
  COLORS.red,
  '#f472b6',
  '#a3e635',
  '#fb923c',
  '#6ee7b7',
  '#94A3B8',
] as const;
